Updating header and footer UI
greenpeace/planet4-child-theme-australiapacific pull request #31
Opened 2023-12-07 08:20 UTC by marlincommuincations

updating the footer column widths + updating the header to be fixed and transparent/white background along with logo resize + removing unwanted scss files

2023-12-10 22:47 UTC, techieshark requested changes
Hi @marlincommuincations thanks for this! Would you mind putting some "How to test" instructions in the PR body - maybe some commands to run so Kara et al can see this locally in their dev environment? Screenshots would be great too! Thanks

2023-12-11 08:46 UTC, marlincommuincations reviewed
PR comment updated.

2023-12-11 23:09 UTC, techieshark commented
@marlincommuincations thanks for updating that PR! I believe @ShoryuDZ and @karabishopgreenpeace will be reviewing this later today!

2023-12-14 07:51 UTC, ShoryuDZ requested changes
I haven't been able to sync content (from ElastiPress?) into the page so I don't have the same content as you at the moment, however I'm still able to see how your changes look over some dummy pages (even if the dummy pages have images in the background which make it difficult to see the menu items when transparent, I can still get a feel for how it is supposed to work).
The main issue I'm seeing at the moment is that when the menu is transparent, the menu items turn the same colour as the background (i.e. White) - making it impossible to see:
![Screenshot 2023-12-14 at 6 47 23 pm](https://github.com/greenpeace/planet4-child-theme-australiapacific/assets/58425525/894eb9e1-1211-4c1f-b615-0d1fedd8cca0)
This doesn't appear the be an issue when the background of the menu is solid white:
![Screenshot 2023-12-14 at 6 47 34 pm](https://github.com/greenpeace/planet4-child-theme-australiapacific/assets/58425525/0ba96a93-f230-4aea-98fa-3497b34c5443)
Let me know if you're able to see/resolve this issue as well, or if you think there's something wrong with my setup.

2023-12-18 02:30 UTC, karabishopgreenpeace commented
Just an FYI @Shoryu Das-Zaman ***@***.***> , the menu
reversed to white is only meant to be on the home page.

On Thu, Dec 14, 2023 at 6:51 PM Shoryu Das-Zaman ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> I haven't been able to sync content (from ElastiPress?) into the page so I
> don't have the same content as you at the moment, however I'm still able to
> see how your changes look over some dummy pages (even if the dummy pages
> have images in the background which make it difficult to see the menu items
> when transparent, I can still get a feel for how it is supposed to work).
> The main issue I'm seeing at the moment is that when the menu is
> transparent, the menu items turn the same colour as the background (i.e.
> White) - making it impossible to see:
> Screenshot.2023-12-14.at.6.47.23.pm.png (view on web)
> <https://github.com/greenpeace/planet4-child-theme-australiapacific/assets/58425525/894eb9e1-1211-4c1f-b615-0d1fedd8cca0>
> This doesn't appear the be an issue when the background of the menu is
> solid white:
> Screenshot.2023-12-14.at.6.47.34.pm.png (view on web)
> <https://github.com/greenpeace/planet4-child-theme-australiapacific/assets/58425525/0ba96a93-f230-4aea-98fa-3497b34c5443>
> Let me know if you're able to see/resolve this issue as well, or if you
> think there's something wrong with my setup.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/greenpeace/planet4-child-theme-australiapacific/pull/31#pullrequestreview-1781228386>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZTX2P4MTJ2CMYJZHQRF4Z3YJKVYZAVCNFSM6AAAAABAKUUYRCVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTOOBRGIZDQMZYGY>
> .
> You are receiving this because you were mentioned.Message ID:
> <greenpeace/planet4-child-theme-australiapacific/pull/31/review/1781228386
> @github.com>
>

2023-12-18 05:45 UTC, ShoryuDZ commented
@karabishopgreenpeace Thanks for letting me know, I will check to see that effect is only happening on the Home page once code has been resubmitted - currently, it is happening on every single page as far as I'm aware

2024-01-08 07:50 UTC, marlincommuincations commented
@ShoryuDZ @techieshark I have gone ahead and updated the menu reserve to only occur on the homepage. All other pages will have the default white background header.

2024-01-12 03:15 UTC, ShoryuDZ approved these changes
Happy with how this looks, thanks @marlincommuincations!

2024-01-21 19:26 UTC, techieshark requested changes
Good morning @marlincommuincations thanks for your extensive work on this! 

I finally had some time to review the code, please see comments in PR. Thank you.

---

Update - comments from myself, Kara & Bianca [in Slack](https://gpap.slack.com/archives/C05QXT9P414/p1705870800686859):

> it feels like the grow/shrink effect is too fast. Ideally the speed matches the speed you are scrolling or something. If I’m slowly scrolling, the shrink should be slow and almost not noticed

> [Re: the logo size transition] Slower would be much nicer if you can change the transition speed. Ideally the white panel would have a transition as well (maybe a fade or slide down if it's easy enough).

Also the alignment / margin on the logo seems to change, so it almost bounces left to right; the left alignment should not change on animation; see this page for example https://donatehubspot.greenpeace.org.au/test-header

2024-01-21 19:26 UTC, techieshark commented on package-lock.json
I don't think package-lock.json needs to change for us to get the UI changes we're after in this PR right? Can this be removed from this PR?

2024-01-22 03:56 UTC, marlincommuincations commented on style/header.scss
> +      width: 260px;
@techieshark These values were provided with the logo resize code solution. These were provided by Kara as this solution was built internally and not within Marlin's scope.

2024-01-22 04:03 UTC, marlincommuincations commented on style/global.scss
> +  padding-top: 0 !important;
Will remove the !important declaration

2024-01-22 04:13 UTC, marlincommuincations commented on js/scripts.js
> +let size = 0;
@techieshark I have updated the variable name

2024-01-22 04:15 UTC, marlincommuincations commented on js/scripts.js
> +	if (document.body.classList.contains('home')) {
@techieshark I have updated the functions.php file to only load the JS file if its the front page.

2024-01-22 04:15 UTC, marlincommuincations commented on js/scripts.js
> +			logo.classList.add('smalllogo');
Spacing has been resolved.

2024-01-22 04:15 UTC, marlincommuincations commented on js/scripts.js
> +  const endOfDocumentTop = 1;
I have renamed the variable to reflect the requirement.

2024-01-22 04:16 UTC, marlincommuincations commented on functions.php
> +  wp_enqueue_script( 'marlin-script', get_stylesheet_directory_uri() .  '/js/scripts.js' );
Script name and handle updated.

2024-01-22 04:16 UTC, marlincommuincations commented on style/global.scss
> +    &:not(.narrow-container) {
I have added in the spacing as a different commit.

2024-01-22 04:28 UTC, marlincommuincations commented on style.css
All the styles in the style.css file are auto generated. Not sure I understand the requirement here.

2024-01-22 04:29 UTC, marlincommuincations commented on js/scripts.js
> +	growShrinkLogo();
@techieshark Happy to update the solution, however this was code provided by Kara as the header modifications are out of scope for Marlin. If the updated solution can be provided I am happy to implement it into the child theme.

2024-01-22 04:30 UTC, marlincommuincations commented on package-lock.json
I have removed the package-lock.json file updates.

2024-01-24 05:19 UTC, techieshark commented on js/scripts.js
> +			logo.classList.add('smalllogo');
Thanks!

2024-01-24 05:23 UTC, techieshark reviewed
hi Adrian! @marlincommuincations thanks very much for addressing some of those requests from our end.

I'm interested in having a pretty clean git commit history (so us or future devs can look back and make sense of everything). 

With that in mind, I wonder if I could trouble you to do the following:

* first make a PR which copies in any files from the master theme you need to alter
* then make a new PR just for the footer bit
* and a different PR for the header changes
* and any changes to the generated style.css file could be in their own git commit with a message header like "Generated style.css" and commit message indicating what command was used to do that conversion from sass to css. 

Thanks!

2024-02-07 22:15 UTC, techieshark commented
Closing as this has been actioned in separate PRs now - thank you!

2024-02-07 22:15 UTC, closed without merging