Allow Gutenberg core blocks
greenpeace/planet4-child-theme-australiapacific pull request #81
Opened 2024-11-04 23:42 UTC by karabishopgreenpeace

# Pull Request Overview
Allow native Gutenberg blocks using code supplied by Japan.  See https://www.notion.so/greenpeaceaustraliapacific/P4-Allow-Gutenberg-Native-Blocks-8f6d40ac30a442a7b023b57f79cebe7e?pvs=4

# 📷 Screenshots

<img width="294" alt="image" src="https://github.com/user-attachments/assets/c13be421-d3ed-414d-a284-fd80dc2ea83a">

## 🤨 Any Issues or Questions?

We will add to this list as we find the names of other blocks.

## 🏁 PR Checklist

Reviewer checklist:
- [ ] ✨ This PR includes new user-facing feature and/or settings
- [ ] 📝 Documentation for new features/settings are in PR description (to go to wiki or Coral docs) 

Contributor checklist:
- [ ] Reference a GitHub issue, Jira ticket, or Notion card in the description 💯
- [ ] 📝 Update the CHANGELOG.md (Put under `[Unreleased]`). Include link to this PR.
- [ ] 📝 Add JSDoc code documentation
- [ ] 🏷 Add flow types. (If needed.)
- [ ] ✅ Add unit tests (`*.test.js`) and/or Cypress Tests.
- [ ] 📖 Create Storybook stories. (For any applicable Components.)
- [ ] 📸 Update snapshots.  Run `yarn test:watch`, press 'a' for "all tests", and "u" to update snaps if needed.
- [ ] Run tests (`yarn test` and `yarn flow`) and clean up any errors 🚀
- [ ] Select 1-2 Reviewers
- [x] Feel good about yourself, you're doing great! 🥳

2024-11-07 10:37 UTC, techieshark requested changes
some easy changes. After these changes unless Ashley jumps in to object, I'd say merge this and test it on the P4 dev site, and if @ashleytowner sees it works there, they can make a release to push to prod. ... but only if it takes less than say 20 minutes, because Kylie says highest priority is the Action Message Endpoint work (aka "CAPI" as you may know it by).

2024-11-07 10:37 UTC, techieshark commented on functions.php
> +	array_push($allowed, 'core/post-title');
consistent whitespace:

```suggestion
  array_push($allowed, 'core/cover');
  array_push($allowed, 'core/post-title');
```

2024-11-07 10:37 UTC, techieshark commented on functions.php
> +function p4_child_theme_gpap_whitelist_blocks( $allowed_blocks, $post ) {
(nit) better name
```suggestion
function p4_child_theme_gpap_add_allowed_blocks( $allowed_blocks, $post ) {
```

2024-11-07 10:37 UTC, techieshark commented on functions.php
> +add_filter('allowed_block_types', 'p4_child_theme_gpap_whitelist_blocks', 11, 2);
better name 

```suggestion
add_filter('allowed_block_types', 'p4_child_theme_gpap_add_allowed_blocks', 11, 2);
```

see https://www.vice.com/en/article/we-need-to-stop-saying-blacklist-and-whitelist/

2024-11-11 02:43 UTC, ashleytowner approved these changes
LGTM

2024-11-11 05:41 UTC, techieshark commented on functions.php
> +add_filter('allowed_block_types', 'p4_child_theme_gpap_whitelist_blocks', 11, 2);
needs to be renamed @ashleytowner @karabishopgreenpeace

2024-11-11 23:23 UTC, techieshark approved these changes
LGTM

2024-11-11 23:23 UTC, ashleytowner approved these changes

2024-11-11 23:26 UTC, merged